<a href="https://colab.research.google.com/github/Hristo2076/it-s-the-math/blob/main/math_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#**Задание 1**

In [ ]:
#Создайте матрицу 3 на 3, заполненную числами от 1 до 9 
matrix_1 = np.random.randint(1,9,size=(3,3))
matrix_1

array([[8, 7, 8],
       [3, 1, 3],
       [2, 3, 6]])

In [ ]:
matrix_2 = np.eye(3)
matrix_2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Прибавьте к ней матрицу с единицами на диагонале 
matrix_3 = matrix_1 + matrix_2
matrix_3

array([[9., 7., 8.],
       [3., 2., 3.],
       [2., 3., 7.]])

In [ ]:
#Умножьте полученную матрицу на вектор (1, 2, 3)
res_1 = np.dot(matrix_3,[1,2,3])
res_1

array([47., 16., 29.])

In [ ]:
aT = matrix_1.T
aT

array([[8, 3, 2],
       [7, 1, 3],
       [8, 3, 6]])

In [ ]:
#Вычислить транспонированную матрицу  от полученной в результате прибавления матрицы 
res_2 = matrix_3 - aT
res_2

array([[ 1.,  4.,  6.],
       [-4.,  1.,  0.],
       [-6.,  0.,  1.]])

In [ ]:
#Посчитайте обратную матрицу к полученной в результате прибавления матрице
res_3 = np.linalg.inv(matrix_3)
res_3

array([[-0.25,  1.25, -0.25],
       [ 0.75, -2.35,  0.15],
       [-0.25,  0.65,  0.15]])

#**Уровень 1:**
**Задание 2**

In [ ]:
#Найдите собственные значения и собственные вектора матрицы:

m = np.array([[2,2],
             [1,3]])
m

array([[2, 2],
       [1, 3]])

In [ ]:
#собственные значения
eigvals_ = np.linalg.eig(m)[0]
eigvals_

array([1., 4.])

In [ ]:
#собственные вектора

self_vec = np.linalg.eig(m)[1]
self_vec

array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]])

**Задание 3** \
Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0. \

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [ ]:
M = np.random.randint(2,8,size=(4,4))
det_ = np.linalg.det(M)
while det_ != 1:
  M = np.random.randint(2,8,size=(4,4))
  det_ = np.linalg.det(M)
print(M,det_)

[[6 2 5 4]
 [3 4 6 3]
 [2 5 4 4]
 [4 6 7 5]] 1.0
